# Generated by Django 5.0.6 on 2025-08-11 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depositos', to='catalogo.taller')),
            ],
            options={
                'unique_together': {('taller', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='RepuestoTaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('original', models.BooleanField(default=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.repuesto')),
                ('taller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.taller')),
            ],
            options={
                'unique_together': {('repuesto', 'taller')},
            },
        ),
        migrations.CreateModel(
            name='StockPorDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('cantidad_minima', models.IntegerField(default=0)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventario.deposito')),
                ('repuesto_taller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventario.repuestotaller')),
            ],
            options={
                'unique_together': {('repuesto_taller', 'deposito')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'INGRESO'), ('EGRESO', 'EGRESO'), ('AJUSTE+', 'AJUSTE+'), ('AJUSTE-', 'AJUSTE-')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('documento', models.CharField(blank=True, max_length=120, null=True)),
                ('externo_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('stock_por_deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.stockpordeposito')),
            ],
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('externo_id', None), _negated=True), fields=('stock_por_deposito', 'externo_id'), name='uq_mov_extid_por_stock'),
        ),
    ]
