# Generated by Django 5.0.6 on 2025-10-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('CRITICO', 'Crítico'), ('MEDIO', 'Medio'), ('ADVERTENCIA', 'Advertencia'), ('INFORMATIVO', 'Informativo')], max_length=20)),
                ('codigo', models.CharField(max_length=50)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('VISTA', 'Vista'), ('DESCARTADA', 'Descartada'), ('RESUELTA', 'Resuelta')], default='NUEVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('datos_snapshot', models.JSONField(blank=True, help_text='Stock, forecast, etc. al momento de la creación', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id_ingreso', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'INGRESO'), ('EGRESO', 'EGRESO'), ('AJUSTE+', 'AJUSTE+'), ('AJUSTE-', 'AJUSTE-'), ('INICIAL+', 'INICIAL+'), ('INICIAL-', 'INICIAL-')], max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('documento', models.CharField(blank=True, max_length=120, null=True)),
                ('externo_id', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivoKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasa_rotacion_objetivo', models.DecimalField(decimal_places=2, default=1.5, help_text='Objetivo de tasa de rotación trimestral', max_digits=5)),
                ('dias_en_mano_objetivo', models.IntegerField(default=60, help_text='Objetivo de días en mano')),
                ('dead_stock_objetivo', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje máximo aceptable de dead stock', max_digits=5)),
                ('dias_dead_stock', models.IntegerField(default=730, help_text='Días sin movimiento para considerar dead stock (2 años)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Objetivo KPI',
                'verbose_name_plural': 'Objetivos KPI',
            },
        ),
        migrations.CreateModel(
            name='StockPorDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
            ],
        ),
    ]
