# Generated by Django 5.0.6 on 2025-10-28 00:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('inventario', '0001_initial'),
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='descartada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alerta',
            name='repuesto_taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='catalogo.repuestotaller'),
        ),
        migrations.AddField(
            model_name='deposito',
            name='taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depositos', to='user.taller'),
        ),
        migrations.AddField(
            model_name='objetivokpi',
            name='grupo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_kpi', to='user.grupo'),
        ),
        migrations.AddField(
            model_name='objetivokpi',
            name='taller',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_kpi', to='user.taller'),
        ),
        migrations.AddField(
            model_name='stockpordeposito',
            name='deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='inventario.deposito'),
        ),
        migrations.AddField(
            model_name='stockpordeposito',
            name='repuesto_taller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='catalogo.repuestotaller'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='stock_por_deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.stockpordeposito'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='id_stock_por_deposito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.stockpordeposito'),
        ),
        migrations.AddConstraint(
            model_name='alerta',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['NUEVA', 'VISTA'])), fields=('repuesto_taller', 'codigo'), name='alerta_activa_unica_por_repuesto_y_codigo'),
        ),
        migrations.AlterUniqueTogether(
            name='alerta',
            unique_together={('repuesto_taller', 'codigo', 'estado')},
        ),
        migrations.AlterUniqueTogether(
            name='deposito',
            unique_together={('taller', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='stockpordeposito',
            unique_together={('repuesto_taller', 'deposito')},
        ),
        migrations.AddConstraint(
            model_name='movimiento',
            constraint=models.UniqueConstraint(condition=models.Q(('externo_id', None), _negated=True), fields=('stock_por_deposito', 'externo_id'), name='uq_mov_extid_por_stock'),
        ),
    ]
