# Generated by Django 5.0.6 on 2025-09-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_stockpordeposito_cantidad_minima_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpordeposito',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stockpordeposito',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
