# Generated by Django 5.0.6 on 2025-10-23 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_stockpordeposito_cantidad_minima_and_more'),
        ('user', '0004_rename_localidad_direccion_ciudad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjetivoKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_calculo', models.CharField(choices=[('unidades', 'Por unidades (cantidades)'), ('valor', 'Por valor monetario (pesos)')], default='valor', help_text='Calcular KPIs en unidades o en valor monetario', max_length=20)),
                ('periodo_calculo', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('anio_calendario', 'Año Calendario (actual)'), ('personalizado', 'Período Personalizado')], default='anual', help_text='Período para calcular la tasa de rotación', max_length=20)),
                ('tipo_periodo', models.CharField(choices=[('movil', 'Ventana móvil (últimos N días)'), ('calendario', 'Período calendario cerrado')], default='movil', help_text='Cómo calcular el período: móvil (desde hoy hacia atrás) o calendario (períodos completos cerrados)', max_length=20)),
                ('fecha_inicio_personalizada', models.DateField(blank=True, help_text='Fecha inicio del período contable', null=True)),
                ('fecha_fin_personalizada', models.DateField(blank=True, help_text='Fecha fin del período contable', null=True)),
                ('tasa_rotacion_objetivo', models.DecimalField(decimal_places=2, default=6.0, help_text='Objetivo de tasa de rotación (veces por período)', max_digits=5)),
                ('dias_en_mano_objetivo', models.IntegerField(default=60, help_text='Objetivo de días en mano')),
                ('dias_dead_stock', models.IntegerField(default=90, help_text='Días sin movimiento para considerar dead stock')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('grupo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_kpi', to='user.grupo')),
                ('taller', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetivo_kpi', to='user.taller')),
            ],
            options={
                'verbose_name': 'Objetivo KPI',
                'verbose_name_plural': 'Objetivos KPI',
            },
        ),
    ]
