# Generated by Django 5.0.6 on 2025-10-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_objetivokpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objetivokpi',
            name='fecha_fin_personalizada',
        ),
        migrations.RemoveField(
            model_name='objetivokpi',
            name='fecha_inicio_personalizada',
        ),
        migrations.RemoveField(
            model_name='objetivokpi',
            name='periodo_calculo',
        ),
        migrations.RemoveField(
            model_name='objetivokpi',
            name='tipo_calculo',
        ),
        migrations.RemoveField(
            model_name='objetivokpi',
            name='tipo_periodo',
        ),
        migrations.AlterField(
            model_name='objetivokpi',
            name='dias_dead_stock',
            field=models.IntegerField(default=730, help_text='Días sin movimiento para considerar dead stock (default: 2 años)'),
        ),
        migrations.AlterField(
            model_name='objetivokpi',
            name='tasa_rotacion_objetivo',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Objetivo de tasa de rotación trimestral (últimos 3 meses)', max_digits=5),
        ),
    ]
