# Generated by Django 5.0.6 on 2025-09-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_stockpordeposito_notas_stockpordeposito_ubicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockpordeposito',
            name='notas',
        ),
        migrations.RemoveField(
            model_name='stockpordeposito',
            name='ubicacion',
        ),
    ]
