# Generated by Django 5.0.6 on 2025-09-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_stockpordeposito_notas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpordeposito',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='stockpordeposito',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
