# Generated by Django 5.0.6 on 2025-10-26 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_objetivokpi_fecha_fin_personalizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivokpi',
            name='dead_stock_objetivo',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje máximo aceptable de dead stock', max_digits=5),
        ),
        migrations.AlterField(
            model_name='objetivokpi',
            name='dias_dead_stock',
            field=models.IntegerField(default=730, help_text='Días sin movimiento para considerar dead stock (2 años)'),
        ),
        migrations.AlterField(
            model_name='objetivokpi',
            name='tasa_rotacion_objetivo',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Objetivo de tasa de rotación trimestral', max_digits=5),
        ),
    ]
