# Generated by Django 5.0.6 on 2025-09-27 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_stockpordeposito_notas_stockpordeposito_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockpordeposito',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockpordeposito',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
