# Generated by Django 5.0.6 on 2025-10-15 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_direccion_pais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='ciudad',
            new_name='localidad',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='codigo_postal',
            new_name='numero',
        ),
    ]
