# Generated by Django 5.0.6 on 2025-10-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_taller_localizacion'),
        ('user', '0004_rename_localidad_direccion_ciudad_and_more'),
    ]

    operations = [
    ]
