# Generated by Django 5.0.6 on 2025-10-28 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('d_externo', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroentrenamiento_frecuencia_alta',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_frecuencia_alta', to='user.taller'),
        ),
        migrations.AddField(
            model_name='registroentrenamiento_intermitente',
            name='taller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros_intermitente', to='user.taller'),
        ),
    ]
